/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_siraudeau;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

/**
 *
 * @author emmas
 */
public class Interface extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Interface.class.getName());
    private CadenasJeu jeu;
    
    private int[] chiffres = {0,0,0,0}; 

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        jeu = new CadenasJeu();
        mettreAJourAffichage();

    }
    
     private void mettreAJourAffichage() {
        texte_chiffre_0.setText("   " + chiffres[0]);
        texte_chiffre_1.setText("   " + chiffres[1]);
        texte_chiffre_2.setText("   " + chiffres[2]);
        texte_chiffre_3.setText("   " + chiffres[3]);

        texte_score.setText(jeu.getTentative() + " sur " + jeu.getMaxTentatives()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_tentatives = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 214, 152, -1));

        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop haut :");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 236, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 258, 160, -1));

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 271, -1, -1));

        texte_tentatives.setText("Tentatives :");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 196, 73, -1));

        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 95, -1, -1));

        jLabel5.setText("Trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        texte_score.setText("   0 sur  5");
        texte_score.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 60, 40));

        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 4, 11, 15));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            jPanel1.add(up_chiffre_1);

            up_chiffre_3.setText("/\\");
                up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_3ActionPerformed(evt);
                    }
                });
                jPanel1.add(up_chiffre_3);

                up_chiffre_2.setText("/\\");
                    up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_2ActionPerformed(evt);
                        }
                    });
                    jPanel1.add(up_chiffre_2);

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(up_chiffre_4);

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_0.setText("    0");
                        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        jPanel1.add(texte_chiffre_0);

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        jPanel1.add(texte_chiffre_2);

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("0 ");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        jPanel1.add(texte_chiffre_1);

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                        texte_chiffre_3.setText("    0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        jPanel1.add(texte_chiffre_3);

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_1);

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_3);

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_2);

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        jPanel1.add(down_chiffre_4);

                        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 320, 140));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        chiffres[1] = (chiffres[1] + 1) % 10;
        mettreAJourAffichage();    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        chiffres[2] = (chiffres[2] + 1) % 10;
        mettreAJourAffichage();     }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        chiffres[3] = (chiffres[3] + 1) % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        chiffres[0] = (chiffres[0] + 1) % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        jeu = new CadenasJeu();
        chiffres = new int[]{0, 0, 0, 0}; 
        mettreAJourAffichage(); 

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        chiffres[0] = (chiffres[0] + 9) % 10 % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        chiffres[1] = (chiffres[1] + 9) % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        chiffres[2] = (chiffres[2] + 9) % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        chiffres[3] = (chiffres[3] + 9) % 10;
        mettreAJourAffichage();
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        jeu.tester(chiffres);

        texte_nb_chiffres_exacts.setText(String.valueOf(jeu.getNbBienPlaces()));
        texte_nb_chiffres_haut.setText(String.valueOf(jeu.getNbTropHauts()));
        texte_nb_chiffres_bas.setText(String.valueOf(jeu.getNbTropBas()));

        texte_score.setText(jeu.getTentative() + " sur " + jeu.getMaxTentatives());

        if (jeu.estGagne()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Félicitations ! Vous avez trouvé le code !");
        } else if (jeu.estTermine()) {
            JOptionPane.showMessageDialog(this, "Partie terminée ! Le code était : " +
                    java.util.Arrays.toString(jeu.getCodeSecret()));
        }
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
