/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FenetreQuiz;

import java.util.ArrayList;


/**
 *
 * @author emmas
 */
public class FenetreQuiz extends javax.swing.JFrame {
    private ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        JLabel_feedback = new javax.swing.JLabel();
        JButton1 = new javax.swing.JButton();
        jLabel_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuestion.setText("Questions");

        btnRep1.setText("Réponse1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Réponse2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("Réponse3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("Réponse4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        JLabel_feedback.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        JLabel_feedback.setText("Feedback");

        JButton1.setText("Question suivante");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });

        jLabel_score.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel_score.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(JLabel_feedback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_score)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRep2)
                        .addGap(12, 12, 12)
                        .addComponent(btnRep3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRep4)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel_score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestion)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep2)
                    .addComponent(btnRep1)
                    .addComponent(btnRep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(JLabel_feedback)
                .addGap(31, 31, 31)
                .addComponent(JButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(0);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
        passerQuestionSuivante();
    }//GEN-LAST:event_JButton1ActionPerformed

    private void passerQuestionSuivante() {
        if (indexQuestionCourante < listeQuestions.size() - 1) {
            indexQuestionCourante++;
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("FIN DU QUIZ !");
            JLabel_feedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
            JButton1.setEnabled(false);
            jLabel_score.setText("Score final : " + score + " / " + listeQuestions.size());
        }
    }

    private void initialiserQuestions() {
        listeQuestions = new ArrayList<>();
 
        listeQuestions.add(new Question("Capital de la France ?", 
                "Paris", "Lyon", "Marseille", "Bordeaux", 0));
        listeQuestions.add(new Question("2 + 2 = ?", 
                "3", "4", "5", "6", 1));
        listeQuestions.add(new Question("Couleur du ciel ?", 
                "Rouge", "Bleu", "Vert", "Jaune", 1));
        listeQuestions.add(new Question("Langage de Java ?", 
                "Interprété", "Binaire", "Assembleur", "Morse", 0));
        listeQuestions.add(new Question("Combien de continents ?", 
                "3", "4", "5", "6", 3));
    }

    private void afficherQuestionCourante() {
        Question q = listeQuestions.get(indexQuestionCourante);

        lblQuestion.setText(q.getIntitule());
        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

        JButton1.setEnabled(false);
        JLabel_feedback.setText("Choisissez une réponse...");
        jLabel_score.setText("Score : " + score + " / " + listeQuestions.size());
    }

    private void verifierReponse(int reponseChoisie) {
        Question q = listeQuestions.get(indexQuestionCourante);

        if (reponseChoisie == q.getIndexBonneReponse()) {
            JLabel_feedback.setText("Bonne réponse !!!");
            score++;
        } else {
            JLabel_feedback.setText("Mauvaise réponse. La bonne réponse était : " + q.getProposition(q.getIndexBonneReponse()) + ".");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);

        JButton1.setEnabled(true);
        jLabel_score.setText("Score : " + score + " / " + (indexQuestionCourante + 1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton1;
    private javax.swing.JLabel JLabel_feedback;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel jLabel_score;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
